---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(limma)
library(pcaMethods)
library(PEMM)
library(missForest)
library(mice)

library(rrcovNA)
library(imputeLCMD)


impute.perseus <- function(x, width=0.3, shift=1.8) {
  # distributions are induced by measured values in each sample
  data.mean <- colMeans(x, na.rm = TRUE)
  data.sd <- matrixStats::colSds(x, na.rm = TRUE)
  n <- nrow(x)
  z <- rmvnorm(n, mean = data.mean - shift*data.sd , sigma = diag(data.sd*width))
  x[is.na(x)] <- z[is.na(x)]
  return(x)
}
```

```{r}
devtools::load_all("/stornext/General/data/academic/lab_davis/prot/benchmarking/msImpute/")

data <- read.delim("/stornext/General/data/academic/lab_davis/prot/benchmarking/PXD014777/HeLa_10_replicates_2hr/evidence.txt", 
                   stringsAsFactors = FALSE)




table(data$Type)
table(grepl("CON_|REV_", data$Leading.razor.protein))
table(data$Charge > 1)


data <- data[grep("CON_|REV_", data$Leading.razor.protein, invert=TRUE),]
data <- data[data$Charge > 1 & (data$Modifications %in% "Unmodified"),]
data$PeptideID <- paste0(data$Modified.sequence, data$Charge)
data$matrix.row.id <- paste(data$PeptideID, data$Leading.Razor.Protein, sep ="_")


genes <- data[,c("PeptideID","matrix.row.id", "Leading.razor.protein")]
genes <- genes[!duplicated(genes),]


y <- evidenceToMatrix(data[data$Type %in% "TIMS-MULTI-MSMS",])


y <- log2(y)
y <- y[rowSums(!is.na(y)) >=4,]

#ensure column names are allowed names
colnames(y) <- gsub("-","_", colnames(y))
genes <- genes[match(rownames(y), genes$PeptideID),]
rownames(y) <- genes$matrix.row.id

```


```{r long_runs, eval = FALSE}
message("LLS")
Sys.time()
y_lls <- llsImpute(t(y))
y_lls <- t(completeObs(y_lls))

message("Imputation in progress")
message("RF")
Sys.time()
y_rf <- missForest(y)
y_rf <- y_rf$ximp



message("Imputation in progress (column-wise imputation)")
message("mice")
Sys.time()
# From mice -----


colnames(y) <- gsub("_","", colnames(y))
colnames(y) <- NULL
y_mice <- mice(y)
y_mice <- complete(y_mice)



message("EM")
Sys.time()
# from PEMM ----
y_em <- PEMM_fun(y, phi=0)$Xhat


message("bpca")
Sys.time()
# From pcaMethods --------
y_bpca <- pca(y, nPcs=2, method="bpca")
y_bpca <- completeObs(y_bpca)

saveRDS(list(y_rf, y_mice, y_em, y_bpca, y_lls), file="impute_HeLa_10_replicate_sOa_filter4obs_noNorm.rds")

```


```{r results='hide', include=TRUE}


group <- as.factor(rep(1:2, each = 5))


y_msImpute <- msImpute(y, 
                       rank.max = 2,
                       method = "v2-mnar",
                       group = group
                       )







y_MLE <- impute.wrapper.MLE(y)
y_impSeq <- impSeq(y)
y_knn <- impute.wrapper.KNN(y, K = 15)


y_minDet <- impute.MinDet(y, q = 0.01)


y_perseus <- impute.perseus(y)



y_qrilc <- impute.QRILC(y, 1)[[1]]


sOa_imps <- readRDS("/stornext/Home/data/allstaff/h/hediyehzadeh.s/softImpute_low_rank_experimentation/impute_HeLa_10_replicate_sOa_filter4obs_noNorm.rds")



names(sOa_imps) <- c("RF","Mice","EM","BPCA","LLS")

sOa_imps <- sOa_imps[c("RF","Mice","EM","BPCA")]

# z <- m <- rownames(sOa_imps[[1]])
# # m <- paste0("_", m)
# 
# rowsname <- rownames(y)[rownames(y) %in% m]



mats <- list(#"MLE"=y_MLE[rowsname,],
             "KNN"= y_knn,
             # "Perseus"= y_perseus[rowsname,],
             # "QRILC" = y_qrilc[rowsname,],
             # "dia" = y_dia,
             "impSeq" = y_impSeq,
             #"PIP_k=2" = y_pip[rowsname,],
             #"PIP_weight" = y_pip_elist[rowsname,],
             "barycenter" = y_msImpute, # [rowsname,]
             #"PIP_barycenter" = y_msImpute_pip, # [rowsname,]
             "baseline" = y)





mats <- c(sOa_imps, mats)

design <- model.matrix(~ group)

n_ups <- 500



fullTables <- list()

for(i in seq_along(mats)){
  message("processing ", names(mats)[i])
   E <- normalizeBetweenArrays(mats[[i]], method = "quantile")

   fit <- lmFit(E, design = design)

   fit <- eBayes(fit)
   print(summary(decideTests(fit)))

  
  
  
  

  fullTables[[names(mats)[i]]] <- fit$p.value[,2]
  

}



fullTables <- do.call(rbind, fullTables)
fullTables <- t(fullTables)

fullTables <- reshape2::melt(fullTables)

fullTables <- fullTables[grep("KNN|baseline", fullTables$Var2, invert = TRUE),]


library(ggplot2)

ggplot(fullTables, aes(x=value)) +
  geom_histogram(fill = "#1F78B4", color = "black") +
  facet_wrap(.~Var2, scales = "free_x") + 
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5), 
        axis.text=element_text(colour="black"),
        axis.ticks = element_line(colour = "black"),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank()
        )

```


